# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Manny <etetopat@student.42bangkok.com>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/16 14:21:27 by Manny             #+#    #+#              #
#    Updated: 2022/11/24 16:17:46 by Manny            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

END = \e[0m
BOLD = \e[1m
UNDER = \e[4m
REV = \e[7m
GREY = \e[30m
RED = \e[31m
GREEN = \e[32m
YELLOW = \e[33m
BLUE = \e[34m
PURPLE = \e[35m
CYAN = \e[36m
WHITE = \e[37m

NAME = so_long

CC = gcc
CFLAGS = -Wall -Wextra -Werror -g3
LIBFT = libft/libft.a
MLX = mlx/libmlx.a
MLXFLAGS = -lmlx -lXext -lX11 -lm -lz
RM = rm -rf