version: "2.24.5"

services:

  mariadb:
    container_name: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb/
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - wp
    volumes:
      - database:/var/lib/mysql/
    restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: ./requirements/wordpress/
      args:
        - MYSQL_HOST
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
        - WP_ADMIN
        - WP_ADMIN_PASSWORD
        - WP_ADMIN_EMAIL
        - WP_USER
        - WP_USER_PASSWORD
        - WP_USER_EMAIL
        - WP_DOMAIN
        - WP_TITLE
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - WP_ADMIN
      - WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_PASSWORD
      - WP_USER_EMAIL
      - WP_DOMAIN
      - WP_TITLE
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    networks:
      - wp
    volumes:
     - wordpress:/var/www/html/
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - wp
    volumes:
      - wordpress:/var/www/html/
    restart: always

networks:
  wp:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/database/

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress/
